controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
live_component:
    ressoure : '@LiveComponentBundle/Ressources/config/routing/live_component.xml'